lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-slate
title: Trekski's Github page
description: Just a way to say hello to the world!
show_downloads: false
